"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.fileTypes = exports.folderTypes = exports.FolderType = exports.FileType = void 0;
var FileType;
(function (FileType) {
    FileType["tsModel"] = "model.ts";
    FileType["tsFunction"] = "function.ts";
    FileType["tsClass"] = "class.ts";
    FileType["ngComponent"] = "component.ts";
    FileType["htmlComponent"] = "component.html";
    FileType["cssComponent"] = "component.css";
    FileType["scssComponent"] = "component.scss";
    FileType["testComponent"] = "component.spec.ts";
    FileType["ngService"] = "service.ts";
    FileType["ngModule"] = "module.ts";
    FileType["ngGuard"] = "guard.ts";
    FileType["tsconfig"] = "tsconfig";
    FileType["eslint"] = "eslint";
    FileType["readme"] = ".md";
    FileType["unknown"] = "unknown";
    FileType["ngInterceptor"] = "interceptor.ts";
    FileType["tsFile"] = ".ts";
})(FileType = exports.FileType || (exports.FileType = {}));
var FolderType;
(function (FolderType) {
    FolderType["controller"] = "controllers";
    FolderType["service"] = "services";
    FolderType["guard"] = "guards";
    FolderType["interceptors"] = "interceptors";
    FolderType["ui"] = "uis";
    FolderType["view"] = "views";
    FolderType["data"] = "data";
    FolderType["core"] = "core";
    FolderType["domain"] = "domains";
    FolderType["test"] = "tests";
    FolderType["style"] = "styles";
    FolderType["util"] = "utils";
    FolderType["feature"] = "features";
    FolderType["model"] = "models";
    FolderType["unknown"] = "unknown";
    FolderType["api"] = "apis";
    FolderType["src"] = "src";
    FolderType["lib"] = "libs";
})(FolderType = exports.FolderType || (exports.FolderType = {}));
exports.folderTypes = Object.values(FolderType);
exports.fileTypes = Object.values(FileType);
//# sourceMappingURL=folder-tree.model.js.map